development:
  adapter: mysql2
  encoding: utf8
  database: RoR_rblog_dev
  pool: 5
  username: padels
  password: padels3005
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: RoR_rblog_test
  pool: 5
  username: padels
  password: padels3005
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: RoR_rblog
  pool: 5
  username: padels
  password: padels3005
  socket: /var/run/mysqld/mysqld.sock

